server:
  port: 8084

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在的路径
  type-aliases-package: com.test.api.entity                # 所有entity别名类所在包
  mapper-locations: classpath*:mybatis/mapper/**/*.xml                     # mapper映射文件

spring:
  application:
    name: springcloud-provider-dept                       # 对外暴露的微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.43.212:3306/test              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka,http://eureka8002.com:8002/eureka,http://eureka8003.com:8003/eureka
  instance:
    instance-id: provider-dept-hystrix
    prefer-ip-address: true  # 显示访问路径

info:
  app:
    name: provider-dept
  company:
    name: http://localhost:8081/eureka
  build:
    artifactId: $project.artifactId$
    version: $project.version$