server:
  port: 8034

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tobeng/spring-cloud-config-test.git #GitHub上面的git仓库名字